### ISSUE TITLE
카테고리 채널 도메인에서 엔티티 속성 정의 및 채널 추가하는 로직 구현

### ISSUE THREAD

**Issue by hyomyeong999** [mtvs-3rd-outsider/master-of-prediction-backend#13]
# 기능 개요

카테고리 채널 도메인 관련된 어그리게이트 , 레포지토리
채널 추가하는 서비스와 테스트 코드 구현 (승인 이후 처리될 insert 만 구현) 

## 세부 개요

필드 임베디드로 구현해서  정책 적용

- 카테고리 채널 이름
- 카테고리 채널 owner user id
- 대표 이미지 1개
- 채널에 대한 간략한 설명
- 채널 규칙
- 채널 가입된 멤버수
- 채널 상태
  - 신청, 승인, 거절, 활성, 비활성

# 구현 리스트
- [x] 어그리게이트
- [x] 레포지토리
- [x] 서비스
- [x] 테스트

**Comment by ghost** [comment]
정해진 팀 규칙에 따라서 커밋메세지 재작성과 코드 정리 후 pr 다시 작성했습니다.
